const Section_Dusk = [
  'This was meant to be a poem',
  'to explain how I feel,',
  'to explain the warmth',
  'that pervades my days,',
  'since you\'ve entered my life.',
  '$',
  'But that felt egocentric.-',
  'Making it all about me',
  'during your special day.',
  '$',
  'Stupidly, I thought-',
  'a simple happy birthday,',
  'and some well wishes,',
  'would surely suffice.@',
  '$',
]
const Section_Night = [
  'But that felt reductive.-',
  'I don\'t want you to just',
  'be happy.-',
  '$',
  'I want you to be happy and I-',
  'want to be there to see it.',
  '$',
]
const Section_NightDeep = [
  'Our story might end with',
  'a bitter goodbye.-',
  '$',
  'Unspoken words.-',
  'Hurt feelings.-',
  '$',
  'It might fade with time.-',
  'Forgotten.-',
  'A piece of paper in the rain.@',
  '$',
  'But- I\'m willing to take the chance.@',
  '$',
]
const Section_Light = [
  'Many ideas have come and gone,',
  'and yet.',
  'I can\'t find the right words.-',
  'Words are just not enough.@',
  '$',
  'So here is my present for you.-',
  'The only thing I can think of',
  'that can express all of that.@',
  '$',
  'The only thing that is left',
  'within me,',
  'when I think of you.',
  '$',
  'Colors.',
]

const lines = [
  'Hey Irma@',
  '$',
  ...Section_Dusk,
  '*',
  ...Section_Night,
  '*',
  ...Section_NightDeep,
  '*',
  ...Section_Light,
  '*',
  '$',
  'Happy birthday',
  '$'
]